### ISSUE TITLE
DONATE Kontrakt QTY begrenzen

### ISSUE THREAD

**Issue by McCompexpert** [EkoDondav/rehaklex#37]
Da es moeglich ist, per default die komplette Sell site abzuraemen, muss man die Einzelordereingabe begrenzen. Sonst "spendet" Dir jemand Hunderte von Euros versehentlich.

**Comment by EkoDondav** [comment]
Stimmt.. die voreingestellte Zahl von 1000 sollte ich fairerweise rausnehmen,
